- hosts: demo
  become: yes
  vars:
    # Map architecture for Docker's repo
    deb_arch: "{{ 'arm64' if ansible_architecture in ['aarch64','arm64'] else 'amd64' }}"
    ubuntu_codename: "{{ ansible_lsb.codename | default('noble') }}"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        update_cache: yes
        state: present

    - name: Make sure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add official Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch={{ deb_arch }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable"
        filename: docker
        state: present

    - name: Install Docker Engine+Compose
      apt:
        update_cache: yes
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu
      loop:
        - /opt/demo
        - /opt/demo/backend
        - /opt/demo/static-site
        - /opt/demo/traefik

    - name: Check acme.json exists with correct permissions
      file:
        path: /opt/demo/traefik/acme.json
        state: touch
        mode: '0600'
        owner: ubuntu
        group: ubuntu

    - name: Copy appication files
      copy:
        src: "../files/"
        dest: "/opt/demo/"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
